export interface EditableConfigField {
  key: string
  label: string
  kind: 'int' | 'float' | 'bool' | 'duration' | 'choice' | 'text'
  defaultValue: string
  liveApplies: boolean
}

export const configFieldDescriptions: Record<string, string> = {
  POLL_INTERVAL_SECONDS: 'How many seconds to wait before polling wallets and markets again.',
  HOT_WALLET_COUNT: 'How many top wallets stay in the fastest polling tier.',
  WARM_WALLET_COUNT: 'How many additional wallets stay in the warm polling tier.',
  WARM_POLL_INTERVAL_MULTIPLIER: 'How much slower warm-wallet polling is than the main poll interval.',
  DISCOVERY_POLL_INTERVAL_MULTIPLIER: 'How much slower discovery polling is than the main poll interval.',
  MAX_MARKET_HORIZON: 'The longest time-to-resolution a market can have and still be eligible.',
  MAX_SOURCE_TRADE_AGE: 'How old a copied source trade can be before we ignore it.',
  MAX_FEED_STALENESS: 'How old market feed data can be before we stop trusting it.',
  MAX_ORDERBOOK_STALENESS: 'How old order book data can be before we stop trusting it.',
  MIN_EXECUTION_WINDOW: 'The minimum time left before resolution needed to place a trade.',
  WALLET_INACTIVITY_LIMIT: 'How long a wallet can stay inactive before it is treated as stale.',
  WALLET_SLOW_DROP_MAX_TRACKING_AGE: 'The oldest slow-tracked wallet age allowed before it can be dropped.',
  WALLET_PERFORMANCE_DROP_MIN_TRADES: 'Minimum copied trades required before weak performance can drop a wallet.',
  WALLET_PERFORMANCE_DROP_MAX_WIN_RATE: 'Maximum copied win rate allowed before the performance-drop rule stops applying.',
  WALLET_PERFORMANCE_DROP_MAX_AVG_RETURN: 'Maximum average copied return allowed before the performance-drop rule stops applying.',
  WALLET_UNCOPYABLE_PENALTY_MIN_BUYS: 'Minimum observed buys required before uncopyable behavior starts shrinking size.',
  WALLET_UNCOPYABLE_PENALTY_WEIGHT: 'How strongly uncopyable behavior reduces wallet sizing.',
  WALLET_UNCOPYABLE_DROP_MIN_BUYS: 'Minimum observed buys required before uncopyable behavior can drop a wallet.',
  WALLET_UNCOPYABLE_DROP_MAX_SKIP_RATE: 'Highest skip rate allowed before uncopyable behavior can drop a wallet.',
  WALLET_UNCOPYABLE_DROP_MAX_RESOLVED_COPIED: 'Maximum resolved copied trades allowed before uncopyable wallets can be dropped.',
  WALLET_COLD_START_MIN_OBSERVED_BUYS: 'Minimum observed buys needed before a wallet leaves cold-start handling.',
  WALLET_DISCOVERY_MIN_OBSERVED_BUYS: 'Minimum observed buys needed before a wallet can enter discovery sizing.',
  WALLET_DISCOVERY_MIN_RESOLVED_BUYS: 'Minimum resolved buys needed before a wallet can enter discovery sizing.',
  WALLET_DISCOVERY_SIZE_MULTIPLIER: 'Position-size multiplier used for wallets still in discovery.',
  WALLET_TRUSTED_MIN_RESOLVED_COPIED_BUYS: 'Minimum resolved copied buys needed before a wallet can become trusted.',
  WALLET_PROBATION_SIZE_MULTIPLIER: 'Position-size multiplier used while a wallet is on probation.',
  WALLET_LOCAL_PERFORMANCE_PENALTY_MIN_RESOLVED_COPIED_BUYS: 'Minimum resolved copied buys needed before local underperformance shrinks size.',
  WALLET_LOCAL_PERFORMANCE_PENALTY_MAX_AVG_RETURN: 'Maximum local average return allowed before we apply the local penalty.',
  WALLET_LOCAL_PERFORMANCE_PENALTY_SIZE_MULTIPLIER: 'Position-size multiplier used when a local performance penalty is active.',
  WALLET_LOCAL_DROP_MIN_RESOLVED_COPIED_BUYS: 'Minimum resolved copied buys needed before local underperformance can drop a wallet.',
  WALLET_LOCAL_DROP_MAX_AVG_RETURN: 'Maximum local average return allowed before the local drop rule can trigger.',
  WALLET_LOCAL_DROP_MAX_TOTAL_PNL_USD: 'Maximum local copied P&L allowed before the local drop rule stops applying.',
  WALLET_QUALITY_SIZE_MIN_MULTIPLIER: 'Lowest wallet-quality multiplier we will allow after quality scaling.',
  WALLET_QUALITY_SIZE_MAX_MULTIPLIER: 'Highest wallet-quality multiplier we will allow after quality scaling.',
  MIN_CONFIDENCE: 'The minimum model confidence a signal must have before it can trade.',
  ALLOWED_ENTRY_PRICE_BANDS: 'Which entry-price bands are globally allowed for trading.',
  ALLOWED_TIME_TO_CLOSE_BANDS: 'Which time-to-close bands are globally allowed for trading.',
  ALLOW_HEURISTIC: 'Whether the heuristic decision path is allowed to place trades.',
  HEURISTIC_MIN_ENTRY_PRICE: 'Lowest entry price the heuristic path is allowed to buy.',
  HEURISTIC_MAX_ENTRY_PRICE: 'Highest entry price the heuristic path is allowed to buy.',
  HEURISTIC_ALLOWED_ENTRY_PRICE_BANDS: 'Which entry-price bands the heuristic path is allowed to use.',
  HEURISTIC_MIN_TIME_TO_CLOSE: 'Minimum time-to-close required before the heuristic path can trade.',
  ALLOW_XGBOOST: 'Whether the XGBoost model path is allowed to place trades.',
  MODEL_EDGE_MID_CONFIDENCE: 'Confidence cutoff that marks the middle model-confidence regime.',
  MODEL_EDGE_HIGH_CONFIDENCE: 'Confidence cutoff that marks the highest model-confidence regime.',
  MODEL_EDGE_MID_THRESHOLD: 'Minimum model edge required in the middle-confidence regime.',
  MODEL_EDGE_HIGH_THRESHOLD: 'Minimum model edge required in the highest-confidence regime.',
  XGBOOST_ALLOWED_ENTRY_PRICE_BANDS: 'Which entry-price bands the model path is allowed to use.',
  MODEL_MIN_TIME_TO_CLOSE: 'Minimum time-to-close required before the model path can trade.',
  MIN_BET_USD: 'Smallest position size allowed for any trade.',
  ENTRY_FIXED_COST_USD: 'Flat dollar cost to assume when entering a position.',
  EXIT_FIXED_COST_USD: 'Flat dollar cost to assume when exiting a position.',
  APPROVAL_FIXED_COST_USD: 'Flat dollar cost to assume when an approval step is required.',
  SETTLEMENT_FIXED_COST_USD: 'Flat dollar cost to assume when a trade settles.',
  EXPECTED_CLOSE_FIXED_COST_USD: 'Flat dollar closing cost to assume when sizing expected exits.',
  INCLUDE_EXPECTED_EXIT_FEE_IN_SIZING: 'Whether expected exit fees should be included in sizing calculations.',
  MAX_BET_FRACTION: 'Largest fraction of bankroll allowed on a single position.',
  MAX_MARKET_EXPOSURE_FRACTION: 'Largest fraction of bankroll allowed in one market.',
  MAX_TRADER_EXPOSURE_FRACTION: 'Largest fraction of bankroll allowed against one copied trader.',
  MAX_TOTAL_OPEN_EXPOSURE_FRACTION: 'Largest fraction of bankroll allowed across all open positions.',
  EXPOSURE_OVERRIDE_TOTAL_CAP_FRACTION: 'Exposure cap used when a trusted-wallet override is active.',
  DUPLICATE_SIDE_OVERRIDE_MIN_SKIPS: 'Minimum skips required before duplicate-side overrides can activate.',
  DUPLICATE_SIDE_OVERRIDE_MIN_AVG_RETURN: 'Minimum average return required before duplicate-side overrides can activate.',
  EXPOSURE_OVERRIDE_MIN_SKIPS: 'Minimum skips required before exposure overrides can activate.',
  EXPOSURE_OVERRIDE_MIN_AVG_RETURN: 'Minimum average return required before exposure overrides can activate.',
  SHADOW_BANKROLL_USD: 'The starting bankroll used for tracker sizing and performance calculations.',
  MAX_DAILY_LOSS_PCT: 'Largest daily drawdown allowed before we stop taking new risk.',
  STOP_LOSS_ENABLED: 'Whether stop-loss exits are enabled for tracked positions.',
  STOP_LOSS_MAX_LOSS_PCT: 'Largest loss allowed before a stop-loss exit is triggered.',
  STOP_LOSS_MIN_HOLD: 'Minimum hold time before a stop-loss exit is allowed to fire.',
  MAX_LIVE_DRAWDOWN_PCT: 'Largest live drawdown allowed before live mode is blocked.',
  MAX_LIVE_HEALTH_FAILURES: 'Maximum live health-check failures allowed before live mode is blocked.',
  LIVE_REQUIRE_SHADOW_HISTORY: 'Whether live mode requires enough shadow-history evidence first.',
  LIVE_MIN_SHADOW_RESOLVED: 'Minimum resolved shadow trades required before live mode can start.',
  RETRAIN_BASE_CADENCE: 'How often the regular model retraining cycle should run.',
  RETRAIN_HOUR_LOCAL: 'Which local hour the scheduled retraining cycle should start.',
  RETRAIN_EARLY_CHECK_INTERVAL: 'How often to check whether an early retrain should run.',
  RETRAIN_MIN_NEW_LABELS: 'How many new labels are needed before an early retrain can trigger.',
  RETRAIN_MIN_SAMPLES: 'Minimum labeled samples required before training a new model.',
  LOG_LEVEL: 'How verbose backend logging should be.',
  MODEL_PATH: 'Filesystem path where the saved model artifact should be loaded from.'
}

export const editableConfigFields: EditableConfigField[] = [
  {key: 'POLL_INTERVAL_SECONDS', label: 'Poll Interval', kind: 'float', defaultValue: '1', liveApplies: true},
  {key: 'HOT_WALLET_COUNT', label: 'Hot Wallet Count', kind: 'int', defaultValue: '12', liveApplies: true},
  {key: 'WARM_WALLET_COUNT', label: 'Warm Wallet Count', kind: 'int', defaultValue: '24', liveApplies: true},
  {key: 'WARM_POLL_INTERVAL_MULTIPLIER', label: 'Warm Poll Mult', kind: 'int', defaultValue: '5', liveApplies: true},
  {key: 'DISCOVERY_POLL_INTERVAL_MULTIPLIER', label: 'Disc Poll Mult', kind: 'int', defaultValue: '20', liveApplies: true},
  {key: 'MAX_MARKET_HORIZON', label: 'Max Market Horizon', kind: 'duration', defaultValue: '3d', liveApplies: true},
  {key: 'MAX_SOURCE_TRADE_AGE', label: 'Source Trade Age', kind: 'duration', defaultValue: '90s', liveApplies: true},
  {key: 'MAX_FEED_STALENESS', label: 'Feed Staleness', kind: 'duration', defaultValue: '90s', liveApplies: true},
  {key: 'MAX_ORDERBOOK_STALENESS', label: 'Book Staleness', kind: 'duration', defaultValue: '3s', liveApplies: true},
  {key: 'MIN_EXECUTION_WINDOW', label: 'Exec Window Min', kind: 'duration', defaultValue: '45s', liveApplies: true},
  {key: 'WALLET_INACTIVITY_LIMIT', label: 'Wallet Inactivity', kind: 'duration', defaultValue: 'unlimited', liveApplies: true},
  {key: 'WALLET_SLOW_DROP_MAX_TRACKING_AGE', label: 'Slow Wallet Max Age', kind: 'duration', defaultValue: 'unlimited', liveApplies: true},
  {key: 'WALLET_PERFORMANCE_DROP_MIN_TRADES', label: 'Wallet Drop Min Trades', kind: 'int', defaultValue: '40', liveApplies: true},
  {key: 'WALLET_PERFORMANCE_DROP_MAX_WIN_RATE', label: 'Wallet Drop Max Win Rate', kind: 'float', defaultValue: '0.40', liveApplies: true},
  {key: 'WALLET_PERFORMANCE_DROP_MAX_AVG_RETURN', label: 'Wallet Drop Max Avg Return', kind: 'float', defaultValue: '-0.03', liveApplies: true},
  {key: 'WALLET_UNCOPYABLE_PENALTY_MIN_BUYS', label: 'Uncopy Penalty Min Buys', kind: 'int', defaultValue: '12', liveApplies: true},
  {key: 'WALLET_UNCOPYABLE_PENALTY_WEIGHT', label: 'Uncopy Penalty Weight', kind: 'float', defaultValue: '0.25', liveApplies: true},
  {key: 'WALLET_UNCOPYABLE_DROP_MIN_BUYS', label: 'Uncopy Drop Min Buys', kind: 'int', defaultValue: '24', liveApplies: true},
  {key: 'WALLET_UNCOPYABLE_DROP_MAX_SKIP_RATE', label: 'Uncopy Drop Max Skip', kind: 'float', defaultValue: '0.75', liveApplies: true},
  {key: 'WALLET_UNCOPYABLE_DROP_MAX_RESOLVED_COPIED', label: 'Uncopy Drop Max Copied', kind: 'int', defaultValue: '3', liveApplies: true},
  {key: 'WALLET_COLD_START_MIN_OBSERVED_BUYS', label: 'Cold Start Min Buys', kind: 'int', defaultValue: '3', liveApplies: true},
  {key: 'WALLET_DISCOVERY_MIN_OBSERVED_BUYS', label: 'Disc Min Buys', kind: 'int', defaultValue: '8', liveApplies: true},
  {key: 'WALLET_DISCOVERY_MIN_RESOLVED_BUYS', label: 'Disc Min Resolved', kind: 'int', defaultValue: '3', liveApplies: true},
  {key: 'WALLET_DISCOVERY_SIZE_MULTIPLIER', label: 'Disc Size Mult', kind: 'float', defaultValue: '0.20', liveApplies: true},
  {key: 'WALLET_TRUSTED_MIN_RESOLVED_COPIED_BUYS', label: 'Trusted Min Copied', kind: 'int', defaultValue: '15', liveApplies: true},
  {key: 'WALLET_PROBATION_SIZE_MULTIPLIER', label: 'Probation Mult', kind: 'float', defaultValue: '0.50', liveApplies: true},
  {key: 'WALLET_LOCAL_PERFORMANCE_PENALTY_MIN_RESOLVED_COPIED_BUYS', label: 'Local Penalty Min', kind: 'int', defaultValue: '15', liveApplies: true},
  {key: 'WALLET_LOCAL_PERFORMANCE_PENALTY_MAX_AVG_RETURN', label: 'Local Penalty Return', kind: 'float', defaultValue: '-0.10', liveApplies: true},
  {key: 'WALLET_LOCAL_PERFORMANCE_PENALTY_SIZE_MULTIPLIER', label: 'Local Penalty Mult', kind: 'float', defaultValue: '0.25', liveApplies: true},
  {key: 'WALLET_LOCAL_DROP_MIN_RESOLVED_COPIED_BUYS', label: 'Local Drop Min', kind: 'int', defaultValue: '12', liveApplies: true},
  {key: 'WALLET_LOCAL_DROP_MAX_AVG_RETURN', label: 'Local Drop Return', kind: 'float', defaultValue: '-0.08', liveApplies: true},
  {key: 'WALLET_LOCAL_DROP_MAX_TOTAL_PNL_USD', label: 'Local Drop P&L', kind: 'float', defaultValue: '0.0', liveApplies: true},
  {key: 'WALLET_QUALITY_SIZE_MIN_MULTIPLIER', label: 'Wallet Quality Min Multiplier', kind: 'float', defaultValue: '0.75', liveApplies: true},
  {key: 'WALLET_QUALITY_SIZE_MAX_MULTIPLIER', label: 'Wallet Quality Max Multiplier', kind: 'float', defaultValue: '1.25', liveApplies: true},
  {key: 'MIN_CONFIDENCE', label: 'Min Confidence', kind: 'float', defaultValue: '0.55', liveApplies: false},
  {key: 'ALLOWED_ENTRY_PRICE_BANDS', label: 'Global Band Allow', kind: 'text', defaultValue: '', liveApplies: true},
  {key: 'ALLOWED_TIME_TO_CLOSE_BANDS', label: 'Global Horizon Allow', kind: 'text', defaultValue: '', liveApplies: true},
  {key: 'ALLOW_HEURISTIC', label: 'Heuristic Enabled', kind: 'bool', defaultValue: 'true', liveApplies: true},
  {key: 'HEURISTIC_MIN_ENTRY_PRICE', label: 'Heuristic Entry Min', kind: 'float', defaultValue: '0.65', liveApplies: true},
  {key: 'HEURISTIC_MAX_ENTRY_PRICE', label: 'Heuristic Entry Max', kind: 'float', defaultValue: '0.75', liveApplies: true},
  {key: 'HEURISTIC_ALLOWED_ENTRY_PRICE_BANDS', label: 'Heuristic Band Allowlist', kind: 'text', defaultValue: '', liveApplies: true},
  {key: 'HEURISTIC_MIN_TIME_TO_CLOSE', label: 'Heur Min Horizon', kind: 'duration', defaultValue: '0s', liveApplies: true},
  {key: 'ALLOW_XGBOOST', label: 'Model Enabled', kind: 'bool', defaultValue: 'true', liveApplies: true},
  {key: 'MODEL_EDGE_MID_CONFIDENCE', label: 'Edge Mid Conf', kind: 'float', defaultValue: '0.55', liveApplies: false},
  {key: 'MODEL_EDGE_HIGH_CONFIDENCE', label: 'Edge High Conf', kind: 'float', defaultValue: '0.65', liveApplies: false},
  {key: 'MODEL_EDGE_MID_THRESHOLD', label: 'Edge Mid Threshold', kind: 'float', defaultValue: '0.0125', liveApplies: false},
  {key: 'MODEL_EDGE_HIGH_THRESHOLD', label: 'Edge High Threshold', kind: 'float', defaultValue: '0.0', liveApplies: false},
  {key: 'XGBOOST_ALLOWED_ENTRY_PRICE_BANDS', label: 'Model Band Allowlist', kind: 'text', defaultValue: '', liveApplies: true},
  {key: 'MODEL_MIN_TIME_TO_CLOSE', label: 'Model Min Horizon', kind: 'duration', defaultValue: '0s', liveApplies: true},
  {key: 'MIN_BET_USD', label: 'Min Bet USD', kind: 'float', defaultValue: '1.00', liveApplies: false},
  {key: 'ENTRY_FIXED_COST_USD', label: 'Entry Fee USD', kind: 'float', defaultValue: '0.00', liveApplies: true},
  {key: 'EXIT_FIXED_COST_USD', label: 'Exit Fee USD', kind: 'float', defaultValue: '0.00', liveApplies: true},
  {key: 'APPROVAL_FIXED_COST_USD', label: 'Approval Fee USD', kind: 'float', defaultValue: '0.00', liveApplies: true},
  {key: 'SETTLEMENT_FIXED_COST_USD', label: 'Settle Fee USD', kind: 'float', defaultValue: '0.00', liveApplies: true},
  {key: 'EXPECTED_CLOSE_FIXED_COST_USD', label: 'Exp Close Fee', kind: 'float', defaultValue: '', liveApplies: true},
  {key: 'INCLUDE_EXPECTED_EXIT_FEE_IN_SIZING', label: 'Size With Exit Fee', kind: 'bool', defaultValue: 'true', liveApplies: true},
  {key: 'MAX_BET_FRACTION', label: 'Max Bet Fraction', kind: 'float', defaultValue: '0.04', liveApplies: false},
  {key: 'MAX_MARKET_EXPOSURE_FRACTION', label: 'Market Exposure Cap', kind: 'float', defaultValue: '0.20', liveApplies: true},
  {key: 'MAX_TRADER_EXPOSURE_FRACTION', label: 'Trader Exposure Cap', kind: 'float', defaultValue: '0.30', liveApplies: true},
  {key: 'MAX_TOTAL_OPEN_EXPOSURE_FRACTION', label: 'Open Exposure Cap', kind: 'float', defaultValue: '0.60', liveApplies: true},
  {key: 'EXPOSURE_OVERRIDE_TOTAL_CAP_FRACTION', label: 'Trusted Exposure Cap', kind: 'float', defaultValue: '0.30', liveApplies: true},
  {key: 'DUPLICATE_SIDE_OVERRIDE_MIN_SKIPS', label: 'Dup Override Min Skips', kind: 'int', defaultValue: '20', liveApplies: true},
  {key: 'DUPLICATE_SIDE_OVERRIDE_MIN_AVG_RETURN', label: 'Dup Override Min Return', kind: 'float', defaultValue: '0.05', liveApplies: true},
  {key: 'EXPOSURE_OVERRIDE_MIN_SKIPS', label: 'Exp Override Min Skips', kind: 'int', defaultValue: '20', liveApplies: true},
  {key: 'EXPOSURE_OVERRIDE_MIN_AVG_RETURN', label: 'Exp Override Min Return', kind: 'float', defaultValue: '0.03', liveApplies: true},
  {key: 'SHADOW_BANKROLL_USD', label: 'Tracker Bankroll', kind: 'float', defaultValue: '1000', liveApplies: false},
  {key: 'MAX_DAILY_LOSS_PCT', label: 'Daily Loss Drawdown', kind: 'float', defaultValue: '0.08', liveApplies: true},
  {key: 'STOP_LOSS_ENABLED', label: 'Stop Loss Enabled', kind: 'bool', defaultValue: 'true', liveApplies: true},
  {key: 'STOP_LOSS_MAX_LOSS_PCT', label: 'Stop Loss Max Loss', kind: 'float', defaultValue: '0.15', liveApplies: true},
  {key: 'STOP_LOSS_MIN_HOLD', label: 'Stop Loss Min Hold', kind: 'duration', defaultValue: '20m', liveApplies: true},
  {key: 'MAX_LIVE_DRAWDOWN_PCT', label: 'Live DD Limit', kind: 'float', defaultValue: '0.15', liveApplies: false},
  {key: 'MAX_LIVE_HEALTH_FAILURES', label: 'Live Health Fails', kind: 'int', defaultValue: '3', liveApplies: false},
  {key: 'LIVE_REQUIRE_SHADOW_HISTORY', label: 'Need Shadow Hist', kind: 'bool', defaultValue: 'true', liveApplies: false},
  {key: 'LIVE_MIN_SHADOW_RESOLVED', label: 'Min Shadow Res', kind: 'int', defaultValue: '100', liveApplies: false},
  {key: 'RETRAIN_BASE_CADENCE', label: 'Retrain Cadence', kind: 'choice', defaultValue: 'daily', liveApplies: false},
  {key: 'RETRAIN_HOUR_LOCAL', label: 'Retrain Hour', kind: 'int', defaultValue: '3', liveApplies: false},
  {key: 'RETRAIN_EARLY_CHECK_INTERVAL', label: 'Early Check', kind: 'duration', defaultValue: '24h', liveApplies: false},
  {key: 'RETRAIN_MIN_NEW_LABELS', label: 'Early Label Gate', kind: 'int', defaultValue: '100', liveApplies: false},
  {key: 'RETRAIN_MIN_SAMPLES', label: 'Train Min Samples', kind: 'int', defaultValue: '200', liveApplies: false},
  {key: 'LOG_LEVEL', label: 'Log Level', kind: 'choice', defaultValue: 'INFO', liveApplies: false},
  {key: 'MODEL_PATH', label: 'Model Path', kind: 'text', defaultValue: 'save/model.joblib', liveApplies: false}
]
