export interface EditableConfigField {
  key: string
  label: string
  kind: 'int' | 'float' | 'bool' | 'duration' | 'choice' | 'text'
  defaultValue: string
  liveApplies: boolean
}

export const editableConfigFields: EditableConfigField[] = [
  {key: 'POLL_INTERVAL_SECONDS', label: 'Poll Interval', kind: 'float', defaultValue: '1', liveApplies: true},
  {key: 'HOT_WALLET_COUNT', label: 'Hot Wallet Count', kind: 'int', defaultValue: '12', liveApplies: true},
  {key: 'WARM_WALLET_COUNT', label: 'Warm Wallet Count', kind: 'int', defaultValue: '24', liveApplies: true},
  {key: 'WARM_POLL_INTERVAL_MULTIPLIER', label: 'Warm Poll Mult', kind: 'int', defaultValue: '5', liveApplies: true},
  {key: 'DISCOVERY_POLL_INTERVAL_MULTIPLIER', label: 'Disc Poll Mult', kind: 'int', defaultValue: '20', liveApplies: true},
  {key: 'MAX_MARKET_HORIZON', label: 'Max Market Horizon', kind: 'duration', defaultValue: '3d', liveApplies: true},
  {key: 'MAX_SOURCE_TRADE_AGE', label: 'Source Trade Age', kind: 'duration', defaultValue: '90s', liveApplies: true},
  {key: 'MAX_FEED_STALENESS', label: 'Feed Staleness', kind: 'duration', defaultValue: '90s', liveApplies: true},
  {key: 'MAX_ORDERBOOK_STALENESS', label: 'Book Staleness', kind: 'duration', defaultValue: '3s', liveApplies: true},
  {key: 'MIN_EXECUTION_WINDOW', label: 'Exec Window Min', kind: 'duration', defaultValue: '45s', liveApplies: true},
  {key: 'WALLET_INACTIVITY_LIMIT', label: 'Wallet Inactivity', kind: 'duration', defaultValue: 'unlimited', liveApplies: true},
  {key: 'WALLET_SLOW_DROP_MAX_TRACKING_AGE', label: 'Slow Wallet Max Age', kind: 'duration', defaultValue: 'unlimited', liveApplies: true},
  {key: 'WALLET_PERFORMANCE_DROP_MIN_TRADES', label: 'Wallet Drop Min Trades', kind: 'int', defaultValue: '40', liveApplies: true},
  {key: 'WALLET_PERFORMANCE_DROP_MAX_WIN_RATE', label: 'Wallet Drop Max Win Rate', kind: 'float', defaultValue: '0.40', liveApplies: true},
  {key: 'WALLET_PERFORMANCE_DROP_MAX_AVG_RETURN', label: 'Wallet Drop Max Avg Return', kind: 'float', defaultValue: '-0.03', liveApplies: true},
  {key: 'WALLET_UNCOPYABLE_PENALTY_MIN_BUYS', label: 'Uncopy Penalty Min Buys', kind: 'int', defaultValue: '12', liveApplies: true},
  {key: 'WALLET_UNCOPYABLE_PENALTY_WEIGHT', label: 'Uncopy Penalty Weight', kind: 'float', defaultValue: '0.25', liveApplies: true},
  {key: 'WALLET_UNCOPYABLE_DROP_MIN_BUYS', label: 'Uncopy Drop Min Buys', kind: 'int', defaultValue: '24', liveApplies: true},
  {key: 'WALLET_UNCOPYABLE_DROP_MAX_SKIP_RATE', label: 'Uncopy Drop Max Skip', kind: 'float', defaultValue: '0.75', liveApplies: true},
  {key: 'WALLET_UNCOPYABLE_DROP_MAX_RESOLVED_COPIED', label: 'Uncopy Drop Max Copied', kind: 'int', defaultValue: '3', liveApplies: true},
  {key: 'WALLET_COLD_START_MIN_OBSERVED_BUYS', label: 'Cold Start Min Buys', kind: 'int', defaultValue: '3', liveApplies: true},
  {key: 'WALLET_DISCOVERY_MIN_OBSERVED_BUYS', label: 'Disc Min Buys', kind: 'int', defaultValue: '8', liveApplies: true},
  {key: 'WALLET_DISCOVERY_MIN_RESOLVED_BUYS', label: 'Disc Min Resolved', kind: 'int', defaultValue: '3', liveApplies: true},
  {key: 'WALLET_DISCOVERY_SIZE_MULTIPLIER', label: 'Disc Size Mult', kind: 'float', defaultValue: '0.20', liveApplies: true},
  {key: 'WALLET_TRUSTED_MIN_RESOLVED_COPIED_BUYS', label: 'Trusted Min Copied', kind: 'int', defaultValue: '15', liveApplies: true},
  {key: 'WALLET_PROBATION_SIZE_MULTIPLIER', label: 'Probation Mult', kind: 'float', defaultValue: '0.50', liveApplies: true},
  {key: 'WALLET_LOCAL_PERFORMANCE_PENALTY_MIN_RESOLVED_COPIED_BUYS', label: 'Local Penalty Min', kind: 'int', defaultValue: '15', liveApplies: true},
  {key: 'WALLET_LOCAL_PERFORMANCE_PENALTY_MAX_AVG_RETURN', label: 'Local Penalty Return', kind: 'float', defaultValue: '-0.10', liveApplies: true},
  {key: 'WALLET_LOCAL_PERFORMANCE_PENALTY_SIZE_MULTIPLIER', label: 'Local Penalty Mult', kind: 'float', defaultValue: '0.25', liveApplies: true},
  {key: 'WALLET_LOCAL_DROP_MIN_RESOLVED_COPIED_BUYS', label: 'Local Drop Min', kind: 'int', defaultValue: '12', liveApplies: true},
  {key: 'WALLET_LOCAL_DROP_MAX_AVG_RETURN', label: 'Local Drop Return', kind: 'float', defaultValue: '-0.08', liveApplies: true},
  {key: 'WALLET_LOCAL_DROP_MAX_TOTAL_PNL_USD', label: 'Local Drop P&L', kind: 'float', defaultValue: '0.0', liveApplies: true},
  {key: 'WALLET_QUALITY_SIZE_MIN_MULTIPLIER', label: 'Wallet Quality Min Multiplier', kind: 'float', defaultValue: '0.75', liveApplies: true},
  {key: 'WALLET_QUALITY_SIZE_MAX_MULTIPLIER', label: 'Wallet Quality Max Multiplier', kind: 'float', defaultValue: '1.25', liveApplies: true},
  {key: 'MIN_CONFIDENCE', label: 'Min Confidence', kind: 'float', defaultValue: '0.55', liveApplies: false},
  {key: 'ALLOWED_ENTRY_PRICE_BANDS', label: 'Global Band Allow', kind: 'text', defaultValue: '', liveApplies: true},
  {key: 'ALLOWED_TIME_TO_CLOSE_BANDS', label: 'Global Horizon Allow', kind: 'text', defaultValue: '', liveApplies: true},
  {key: 'ALLOW_HEURISTIC', label: 'Heuristic Enabled', kind: 'bool', defaultValue: 'true', liveApplies: true},
  {key: 'HEURISTIC_MIN_ENTRY_PRICE', label: 'Heuristic Entry Min', kind: 'float', defaultValue: '0.65', liveApplies: true},
  {key: 'HEURISTIC_MAX_ENTRY_PRICE', label: 'Heuristic Entry Max', kind: 'float', defaultValue: '0.75', liveApplies: true},
  {key: 'HEURISTIC_ALLOWED_ENTRY_PRICE_BANDS', label: 'Heuristic Band Allowlist', kind: 'text', defaultValue: '', liveApplies: true},
  {key: 'HEURISTIC_MIN_TIME_TO_CLOSE', label: 'Heur Min Horizon', kind: 'duration', defaultValue: '0s', liveApplies: true},
  {key: 'ALLOW_XGBOOST', label: 'Model Enabled', kind: 'bool', defaultValue: 'true', liveApplies: true},
  {key: 'MODEL_EDGE_MID_CONFIDENCE', label: 'Edge Mid Conf', kind: 'float', defaultValue: '0.55', liveApplies: false},
  {key: 'MODEL_EDGE_HIGH_CONFIDENCE', label: 'Edge High Conf', kind: 'float', defaultValue: '0.65', liveApplies: false},
  {key: 'MODEL_EDGE_MID_THRESHOLD', label: 'Edge Mid Threshold', kind: 'float', defaultValue: '0.0125', liveApplies: false},
  {key: 'MODEL_EDGE_HIGH_THRESHOLD', label: 'Edge High Threshold', kind: 'float', defaultValue: '0.0', liveApplies: false},
  {key: 'XGBOOST_ALLOWED_ENTRY_PRICE_BANDS', label: 'Model Band Allowlist', kind: 'text', defaultValue: '', liveApplies: true},
  {key: 'MODEL_MIN_TIME_TO_CLOSE', label: 'Model Min Horizon', kind: 'duration', defaultValue: '0s', liveApplies: true},
  {key: 'MIN_BET_USD', label: 'Min Bet USD', kind: 'float', defaultValue: '1.00', liveApplies: false},
  {key: 'ENTRY_FIXED_COST_USD', label: 'Entry Fee USD', kind: 'float', defaultValue: '0.00', liveApplies: true},
  {key: 'EXIT_FIXED_COST_USD', label: 'Exit Fee USD', kind: 'float', defaultValue: '0.00', liveApplies: true},
  {key: 'APPROVAL_FIXED_COST_USD', label: 'Approval Fee USD', kind: 'float', defaultValue: '0.00', liveApplies: true},
  {key: 'SETTLEMENT_FIXED_COST_USD', label: 'Settle Fee USD', kind: 'float', defaultValue: '0.00', liveApplies: true},
  {key: 'EXPECTED_CLOSE_FIXED_COST_USD', label: 'Exp Close Fee', kind: 'float', defaultValue: '', liveApplies: true},
  {key: 'INCLUDE_EXPECTED_EXIT_FEE_IN_SIZING', label: 'Size With Exit Fee', kind: 'bool', defaultValue: 'true', liveApplies: true},
  {key: 'MAX_BET_FRACTION', label: 'Max Bet Fraction', kind: 'float', defaultValue: '0.04', liveApplies: false},
  {key: 'MAX_MARKET_EXPOSURE_FRACTION', label: 'Market Exposure Cap', kind: 'float', defaultValue: '20', liveApplies: true},
  {key: 'MAX_TRADER_EXPOSURE_FRACTION', label: 'Trader Exposure Cap', kind: 'float', defaultValue: '30', liveApplies: true},
  {key: 'MAX_TOTAL_OPEN_EXPOSURE_FRACTION', label: 'Open Exposure Cap', kind: 'float', defaultValue: '25', liveApplies: true},
  {key: 'EXPOSURE_OVERRIDE_TOTAL_CAP_FRACTION', label: 'Trusted Exposure Cap', kind: 'float', defaultValue: '30', liveApplies: true},
  {key: 'DUPLICATE_SIDE_OVERRIDE_MIN_SKIPS', label: 'Dup Override Min Skips', kind: 'int', defaultValue: '20', liveApplies: true},
  {key: 'DUPLICATE_SIDE_OVERRIDE_MIN_AVG_RETURN', label: 'Dup Override Min Return', kind: 'float', defaultValue: '0.05', liveApplies: true},
  {key: 'EXPOSURE_OVERRIDE_MIN_SKIPS', label: 'Exp Override Min Skips', kind: 'int', defaultValue: '20', liveApplies: true},
  {key: 'EXPOSURE_OVERRIDE_MIN_AVG_RETURN', label: 'Exp Override Min Return', kind: 'float', defaultValue: '0.03', liveApplies: true},
  {key: 'SHADOW_BANKROLL_USD', label: 'Tracker Bankroll', kind: 'float', defaultValue: '1000', liveApplies: false},
  {key: 'MAX_DAILY_LOSS_PCT', label: 'Daily Loss Drawdown', kind: 'float', defaultValue: '5', liveApplies: true},
  {key: 'STOP_LOSS_ENABLED', label: 'Stop Loss Enabled', kind: 'bool', defaultValue: 'true', liveApplies: true},
  {key: 'STOP_LOSS_MAX_LOSS_PCT', label: 'Stop Loss Max Loss', kind: 'float', defaultValue: '15', liveApplies: true},
  {key: 'STOP_LOSS_MIN_HOLD', label: 'Stop Loss Min Hold', kind: 'duration', defaultValue: '20m', liveApplies: true},
  {key: 'MAX_LIVE_DRAWDOWN_PCT', label: 'Live DD Limit', kind: 'float', defaultValue: '15', liveApplies: false},
  {key: 'MAX_LIVE_HEALTH_FAILURES', label: 'Live Health Fails', kind: 'int', defaultValue: '3', liveApplies: false},
  {key: 'LIVE_REQUIRE_SHADOW_HISTORY', label: 'Need Shadow Hist', kind: 'bool', defaultValue: 'true', liveApplies: false},
  {key: 'LIVE_MIN_SHADOW_RESOLVED', label: 'Min Shadow Res', kind: 'int', defaultValue: '100', liveApplies: false},
  {key: 'RETRAIN_BASE_CADENCE', label: 'Retrain Cadence', kind: 'choice', defaultValue: 'daily', liveApplies: false},
  {key: 'RETRAIN_HOUR_LOCAL', label: 'Retrain Hour', kind: 'int', defaultValue: '3', liveApplies: false},
  {key: 'RETRAIN_EARLY_CHECK_INTERVAL', label: 'Early Check', kind: 'duration', defaultValue: '24h', liveApplies: false},
  {key: 'RETRAIN_MIN_NEW_LABELS', label: 'Early Label Gate', kind: 'int', defaultValue: '100', liveApplies: false},
  {key: 'RETRAIN_MIN_SAMPLES', label: 'Train Min Samples', kind: 'int', defaultValue: '200', liveApplies: false},
  {key: 'LOG_LEVEL', label: 'Log Level', kind: 'choice', defaultValue: 'INFO', liveApplies: false},
  {key: 'MODEL_PATH', label: 'Model Path', kind: 'text', defaultValue: 'save/model.joblib', liveApplies: false}
]
