import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { envFileName, envProfile } from './envProfile.js';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
export const dashboardDir = __dirname;
export const projectRoot = path.resolve(dashboardDir, '..');
export const saveDir = path.resolve(projectRoot, 'save');
export const dataDir = path.resolve(saveDir, 'data');
export const dbPath = path.resolve(dataDir, 'trading.db');
export const eventsPath = path.resolve(dataDir, 'events.jsonl');
export const identityPath = path.resolve(dataDir, 'identity_cache.json');
export const botStatePath = path.resolve(dataDir, 'bot_state.json');
export const retrainRequestPath = path.resolve(dataDir, 'manual_retrain_request.json');
export const manualTradeRequestPath = path.resolve(dataDir, 'manual_trade_request.json');
export const envPath = path.resolve(projectRoot, envFileName);
export const configEnvPath = path.resolve(projectRoot, 'kelly-config.env');
export const secretsEnvPath = path.resolve(projectRoot, 'kelly-secrets.env');
export const envExamplePath = path.resolve(projectRoot, 'kelly-config.env.example');
const splitEnvReadPaths = [configEnvPath, secretsEnvPath].filter((candidate) => fs.existsSync(candidate));
export const envReadPaths = splitEnvReadPaths;
void envProfile;
export const envReadPath = envReadPaths[0] || envExamplePath;
