from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
APP_PATH = ROOT / "dashboard-web" / "src" / "App.tsx"
API_PATH = ROOT / "dashboard-web" / "src" / "api.ts"
MOCK_PATH = ROOT / "dashboard-web" / "src" / "mockDashboard.ts"
STYLES_PATH = ROOT / "dashboard-web" / "src" / "styles.css"
FEED_UTILS_PATH = ROOT / "dashboard-web" / "src" / "feedUtils.ts"
TRACKER_PATH = ROOT / "dashboard-web" / "src" / "trackerFeed.tsx"
SIGNALS_PATH = ROOT / "dashboard-web" / "src" / "signalsFeed.tsx"
INDEX_PATH = ROOT / "dashboard-web" / "index.html"


class DashboardWebSourceTests(unittest.TestCase):
    def test_api_contract_includes_recovery_integrity_archive_and_storage_fields(self) -> None:
        source = API_PATH.read_text(encoding="utf-8")
        self.assertIn("configured_mode?: 'shadow' | 'live'", source)
        self.assertIn("mode_block_reason?: string", source)
        self.assertIn("startup_failed?: boolean", source)
        self.assertIn("startup_validation_failed?: boolean", source)
        self.assertIn("startup_detail?: string", source)
        self.assertIn("startup_failure_message?: string", source)
        self.assertIn("db_recovery_candidate_path?: string", source)
        self.assertIn("db_recovery_candidate_source_path?: string", source)
        self.assertIn("db_recovery_candidate_class_reason?: string", source)
        self.assertIn("db_recovery_latest_verified_backup_path?: string", source)
        self.assertIn("db_recovery_latest_verified_backup_at?: number", source)
        self.assertIn("db_recovery_inventory?: DbRecoveryInventoryEntry[]", source)
        self.assertIn("db_recovery_inventory_count?: number", source)
        self.assertIn("startup_recovery_only?: boolean", source)
        self.assertIn("startup_block_reason?: string", source)
        self.assertIn("db_integrity_message?: string", source)
        self.assertIn("trade_log_archive_cutoff_ts?: number", source)
        self.assertIn("trade_log_archive_preserve_since_ts?: number", source)
        self.assertIn("trade_log_archive_last_candidate_count?: number", source)
        self.assertIn("trade_log_archive_last_vacuumed?: boolean", source)
        self.assertIn("shadow_snapshot_block_reason?: string", source)
        self.assertIn("trade_log_archive_status?: string", source)
        self.assertIn("trade_log_archive_active_db_allocated_bytes?: number", source)
        self.assertIn("storage_trading_db_allocated_bytes?: number", source)
        self.assertIn("db_recovery_candidate_mode?: string", source)
        self.assertIn("post_promotion_promoted_at?: number", source)
        self.assertIn("post_promotion_baseline_at?: number", source)
        self.assertIn("post_promotion_boundary_action?: string", source)
        self.assertIn("post_promotion_boundary_source?: string", source)
        self.assertIn("post_promotion_boundary_reason?: string", source)
        self.assertIn("post_promotion_timing_skips?: number", source)
        self.assertIn("post_promotion_liquidity_skips?: number", source)
        self.assertIn("post_promotion_uncopyable_skip_rate?: number", source)
        self.assertIn("post_promotion_resolved_copied_count?: number", source)
        self.assertIn("post_promotion_resolved_copied_total_pnl_usd?: number", source)
        self.assertIn("post_promotion_evidence_ready?: boolean", source)
        self.assertIn("post_promotion_evidence_note?: string", source)
        self.assertIn("trust_tier?: string", source)
        self.assertIn("trust_size_multiplier?: number", source)
        self.assertIn("trust_note?: string", source)
        self.assertIn("export interface ConfigRow", source)
        self.assertIn("export interface ConfigSnapshot", source)

    def test_mock_dashboard_defaults_dev_to_local_template_mode(self) -> None:
        source = MOCK_PATH.read_text(encoding="utf-8")
        self.assertIn("export const dashboardDataMode", source)
        self.assertIn("rawMode === 'api' ? 'api' : import.meta.env.DEV ? 'mock' : 'api'", source)
        self.assertIn("{id: 'tracker', label: 'Tracker'}", source)
        self.assertIn("{id: 'signals', label: 'Signals'}", source)
        self.assertIn("{id: 'perf', label: 'Perf'}", source)
        self.assertIn("{id: 'models', label: 'Models'}", source)
        self.assertIn("{id: 'wallets', label: 'Wallets'}", source)
        self.assertIn("{id: 'config', label: 'Config'}", source)
        self.assertIn("trackerEvents: LiveEvent[]", source)
        self.assertIn("signalEvents: LiveEvent[]", source)
        self.assertIn("type: 'incoming'", source)
        self.assertIn("type: 'signal'", source)
        self.assertIn("trade-1001", source)

    def test_app_is_minimal_nav_shell_and_not_the_old_operator_dashboard(self) -> None:
        source = APP_PATH.read_text(encoding="utf-8")
        self.assertIn("kelly-watcher", source)
        self.assertIn("Dashboard pages", source)
        self.assertIn("dashboardModel.pages.map", source)
        self.assertIn("topbar__nav", source)
        self.assertIn("page-canvas", source)
        self.assertIn("<TrackerFeed mode={dashboardModel.mode} mockEvents={dashboardModel.trackerEvents} />", source)
        self.assertIn("<SignalsFeed mode={dashboardModel.mode} mockEvents={dashboardModel.signalEvents} />", source)
        self.assertNotIn("One backend, two frontends", source)
        self.assertNotIn("Recovery, integrity, and storage truth", source)
        self.assertNotIn("/api/config", source)
        self.assertNotIn("Restart Shadow", source)
        self.assertNotIn("Config Repair", source)

    def test_feed_utils_own_shared_event_polling(self) -> None:
        source = FEED_UTILS_PATH.read_text(encoding="utf-8")
        self.assertIn("fetchApiJson<EventsResponse>", source)
        self.assertIn("'/api/events?max=250'", source)
        self.assertIn("export function useEventFeed", source)
        self.assertIn("export function normalizeReasonText", source)
        self.assertIn("export function resolveActionText", source)
        self.assertIn("export function buildTradeIdLookup", source)

    def test_tracker_feed_ports_cli_columns_using_semantic_table_layout(self) -> None:
        source = TRACKER_PATH.read_text(encoding="utf-8")
        self.assertIn("const TRACKER_COLUMNS: TrackerColumn[] = [", source)
        self.assertIn("events.filter((event) => event.type === 'incoming').reverse()", source)
        self.assertIn("<table className=\"tracker-table\">", source)
        self.assertIn("<colgroup>", source)
        self.assertIn("TRACKER_COLUMNS.map((column) => (", source)
        self.assertIn("label: 'ID'", source)
        self.assertIn("label: 'TIME'", source)
        self.assertIn("label: 'USERNAME'", source)
        self.assertIn("label: 'MARKET'", source)
        self.assertIn("label: 'ACTN'", source)
        self.assertIn("label: 'SIDE'", source)
        self.assertIn("label: 'PRICE'", source)
        self.assertIn("label: 'SHARES'", source)
        self.assertIn("label: 'PAID'", source)
        self.assertIn("label: 'TO WIN'", source)
        self.assertIn("label: 'PROFIT'", source)
        self.assertIn("probabilityColor(event.price)", source)
        self.assertIn("positiveDollarColor", source)
        self.assertIn("outcomeColor", source)
        self.assertNotIn("TRACKER_TABLE_WIDTH", source)
        self.assertNotIn("gridTemplateColumns", source)

    def test_signals_feed_ports_cli_columns_using_semantic_table_layout(self) -> None:
        source = SIGNALS_PATH.read_text(encoding="utf-8")
        self.assertIn("const SIGNALS_COLUMNS: SignalsColumn[] = [", source)
        self.assertIn("events.filter((event) => event.type === 'signal').reverse()", source)
        self.assertIn("event.type === 'incoming' && event.action?.trim()", source)
        self.assertIn("<table className=\"signals-table\">", source)
        self.assertIn("<colgroup>", source)
        self.assertIn("SIGNALS_COLUMNS.map((column) => (", source)
        self.assertIn("label: 'ID'", source)
        self.assertIn("label: 'TIME'", source)
        self.assertIn("label: 'USERNAME'", source)
        self.assertIn("label: 'MARKET'", source)
        self.assertIn("label: 'ACTN'", source)
        self.assertIn("label: 'SIDE'", source)
        self.assertIn("label: 'PRICE'", source)
        self.assertIn("label: 'SHARES'", source)
        self.assertIn("label: 'TOTAL'", source)
        self.assertIn("label: 'DEC'", source)
        self.assertIn("label: 'CONF'", source)
        self.assertIn("label: 'REASON'", source)
        self.assertIn("decisionColor", source)
        self.assertIn("normalizeReasonText", source)
        self.assertIn("probabilityColor", source)
        self.assertIn("outcomeColor", source)

    def test_styles_are_now_a_solid_background_with_simple_topbar(self) -> None:
        source = STYLES_PATH.read_text(encoding="utf-8")
        self.assertIn("--bg: #0f0f0f;", source)
        self.assertIn("background: var(--bg);", source)
        self.assertIn("text-transform: uppercase;", source)
        self.assertIn(".topbar {", source)
        self.assertIn(".topbar__link--active {", source)
        self.assertIn("border-right: 1px solid var(--border);", source)
        self.assertIn(".tracker-table,", source)
        self.assertIn(".signals-table {", source)
        self.assertIn("width: max-content;", source)
        self.assertIn("min-width: 100%;", source)
        self.assertIn("font-variant-numeric: tabular-nums;", source)
        self.assertIn(".tracker-page__viewport,", source)
        self.assertIn(".signals-cell--reason {", source)
        self.assertIn("min-width: 32rem;", source)
        self.assertIn("white-space: nowrap;", source)
        self.assertNotIn("border-radius: 999px;", source)
        self.assertNotIn("radial-gradient", source)
        self.assertNotIn("body::before", source)
        self.assertNotIn("body::after", source)

    def test_browser_tab_title_stays_lowercase(self) -> None:
        source = INDEX_PATH.read_text(encoding="utf-8")
        self.assertIn("<title>kelly-watcher</title>", source)
        self.assertNotIn("<title>Kelly Watcher Web Dashboard</title>", source)


if __name__ == "__main__":
    unittest.main()
