from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
APP_PATH = ROOT / "dashboard-web" / "src" / "App.tsx"
API_PATH = ROOT / "dashboard-web" / "src" / "api.ts"


class DashboardWebSourceTests(unittest.TestCase):
    def test_api_contract_includes_recovery_integrity_archive_and_storage_fields(self) -> None:
        source = API_PATH.read_text(encoding="utf-8")
        self.assertIn("configured_mode?: 'shadow' | 'live'", source)
        self.assertIn("mode_block_reason?: string", source)
        self.assertIn("startup_failed?: boolean", source)
        self.assertIn("startup_validation_failed?: boolean", source)
        self.assertIn("startup_detail?: string", source)
        self.assertIn("startup_failure_message?: string", source)
        self.assertIn("db_recovery_candidate_path?: string", source)
        self.assertIn("db_recovery_candidate_source_path?: string", source)
        self.assertIn("db_recovery_candidate_class_reason?: string", source)
        self.assertIn("db_recovery_latest_verified_backup_path?: string", source)
        self.assertIn("db_recovery_latest_verified_backup_at?: number", source)
        self.assertIn("db_recovery_inventory?: DbRecoveryInventoryEntry[]", source)
        self.assertIn("db_recovery_inventory_count?: number", source)
        self.assertIn("startup_recovery_only?: boolean", source)
        self.assertIn("startup_block_reason?: string", source)
        self.assertIn("db_integrity_message?: string", source)
        self.assertIn("trade_log_archive_cutoff_ts?: number", source)
        self.assertIn("trade_log_archive_preserve_since_ts?: number", source)
        self.assertIn("trade_log_archive_last_candidate_count?: number", source)
        self.assertIn("trade_log_archive_last_vacuumed?: boolean", source)
        self.assertIn("shadow_snapshot_block_reason?: string", source)
        self.assertIn("trade_log_archive_status?: string", source)
        self.assertIn("trade_log_archive_active_db_allocated_bytes?: number", source)
        self.assertIn("storage_trading_db_allocated_bytes?: number", source)
        self.assertIn("db_recovery_candidate_mode?: string", source)
        self.assertIn("post_promotion_promoted_at?: number", source)
        self.assertIn("post_promotion_baseline_at?: number", source)
        self.assertIn("post_promotion_boundary_action?: string", source)
        self.assertIn("post_promotion_boundary_source?: string", source)
        self.assertIn("post_promotion_boundary_reason?: string", source)
        self.assertIn("post_promotion_timing_skips?: number", source)
        self.assertIn("post_promotion_liquidity_skips?: number", source)
        self.assertIn("post_promotion_uncopyable_skip_rate?: number", source)
        self.assertIn("post_promotion_resolved_copied_count?: number", source)
        self.assertIn("post_promotion_resolved_copied_total_pnl_usd?: number", source)
        self.assertIn("post_promotion_evidence_ready?: boolean", source)
        self.assertIn("post_promotion_evidence_note?: string", source)
        self.assertIn("trust_tier?: string", source)
        self.assertIn("trust_size_multiplier?: number", source)
        self.assertIn("trust_note?: string", source)

    def test_app_surfaces_fail_closed_operational_panel_and_no_cli_copy(self) -> None:
        source = APP_PATH.read_text(encoding="utf-8")
        self.assertIn("Recovery, integrity, and storage truth", source)
        self.assertIn("configured LIVE", source)
        self.assertIn("/api/live-mode", source)
        self.assertIn("/api/shadow/restart", source)
        self.assertIn("/api/shadow/recover-db", source)
        self.assertIn("/api/shadow/archive-trade-log", source)
        self.assertIn("Restart Shadow", source)
        self.assertIn("Restart Shadow ({humanizeStatus(shadowRestartWalletMode)}):", source)
        self.assertIn("Reset wallets", source)
        self.assertIn("Keep active", source)
        self.assertIn("Keep all", source)
        self.assertIn("Clear all", source)
        self.assertIn("Recover DB", source)
        self.assertIn("Recover DB:", source)
        self.assertIn("Archive Trade Log", source)
        self.assertIn("Archive Trade Log:", source)
        self.assertIn("Set Shadow-Only", source)
        self.assertIn("Set Shadow-Only:", source)
        self.assertIn("Startup validation failed", source)
        self.assertIn("Startup Failed", source)
        self.assertIn("Startup Issues", source)
        self.assertIn("Startup issue:", source)
        self.assertIn("Startup warning:", source)
        self.assertIn("Wallet registry queries are paused:", source)
        self.assertIn("managedWalletsResource.data?.message?.trim()", source)
        self.assertIn("Discovery queries are paused:", source)
        self.assertIn("Wallet timeline queries are paused:", source)
        self.assertIn("Mode policy:", source)
        self.assertIn("Mode override:", source)
        self.assertIn("Latest Backup", source)
        self.assertIn("Recovery Inventory", source)
        self.assertIn("Recovery Candidate:", source)
        self.assertIn("Archive Window", source)
        self.assertIn("Archive Result", source)
        self.assertIn("Another dashboard action is already in progress.", source)
        self.assertIn("awaiting proof", source)
        self.assertIn("Trust:", source)
        self.assertIn("Trust pending", source)
        self.assertIn("proof reset by reactivation", source)
        self.assertIn("proof reset by shadow reset", source)
        self.assertIn("auto-promoted ${formatRelativeSeconds(wallet.post_promotion_promoted_at)}", source)
        self.assertIn("promoted ${formatRelativeSeconds(wallet.post_promotion_baseline_at)}", source)
        self.assertIn("Boundary: ${humanizeStatus(wallet.post_promotion_boundary_action, 'Promote')}", source)
        self.assertIn("wallet.post_promotion_evidence_note", source)
        self.assertIn("Auto-Promoted", source)
        self.assertIn("Awaiting Proof", source)
        self.assertIn("Evidence Ready", source)
        self.assertIn("Ready Rate", source)
        self.assertIn("Copy Quality", source)
        self.assertIn("Post-Promotion P&L", source)
        self.assertIn("Active Promoted", source)
        self.assertIn("Execution Drag", source)
        self.assertIn("Drag Causes", source)
        self.assertIn("Probation Blockers", source)
        self.assertIn("Queries paused •", source)
        self.assertIn("Event feed is paused:", source)
        self.assertIn("Trade log DB:", source)
        self.assertIn("Archive rows: active", source)
        self.assertNotIn("One backend, two frontends", source)


if __name__ == "__main__":
    unittest.main()
