from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
APP_PATH = ROOT / "dashboard-web" / "src" / "App.tsx"
API_PATH = ROOT / "dashboard-web" / "src" / "api.ts"
MOCK_PATH = ROOT / "dashboard-web" / "src" / "mockDashboard.ts"
STYLES_PATH = ROOT / "dashboard-web" / "src" / "styles.css"
FEED_UTILS_PATH = ROOT / "dashboard-web" / "src" / "feedUtils.ts"
CONFIG_FIELDS_PATH = ROOT / "dashboard-web" / "src" / "configFields.ts"
TRACKER_PATH = ROOT / "dashboard-web" / "src" / "trackerFeed.tsx"
SIGNALS_PATH = ROOT / "dashboard-web" / "src" / "signalsFeed.tsx"
PAGES_PATH = ROOT / "dashboard-web" / "src" / "dashboardPages.tsx"
COLUMN_RESIZE_PATH = ROOT / "dashboard-web" / "src" / "columnResize.ts"
INDEX_PATH = ROOT / "dashboard-web" / "index.html"


class DashboardWebSourceTests(unittest.TestCase):
    def test_api_contract_includes_recovery_integrity_archive_and_storage_fields(self) -> None:
        source = API_PATH.read_text(encoding="utf-8")
        self.assertIn("configured_mode?: 'shadow' | 'live'", source)
        self.assertIn("mode_block_reason?: string", source)
        self.assertIn("startup_failed?: boolean", source)
        self.assertIn("startup_validation_failed?: boolean", source)
        self.assertIn("startup_detail?: string", source)
        self.assertIn("startup_failure_message?: string", source)
        self.assertIn("db_recovery_candidate_path?: string", source)
        self.assertIn("db_recovery_candidate_source_path?: string", source)
        self.assertIn("db_recovery_candidate_class_reason?: string", source)
        self.assertIn("db_recovery_latest_verified_backup_path?: string", source)
        self.assertIn("db_recovery_latest_verified_backup_at?: number", source)
        self.assertIn("db_recovery_inventory?: DbRecoveryInventoryEntry[]", source)
        self.assertIn("db_recovery_inventory_count?: number", source)
        self.assertIn("startup_recovery_only?: boolean", source)
        self.assertIn("startup_block_reason?: string", source)
        self.assertIn("db_integrity_message?: string", source)
        self.assertIn("trade_log_archive_cutoff_ts?: number", source)
        self.assertIn("trade_log_archive_preserve_since_ts?: number", source)
        self.assertIn("trade_log_archive_last_candidate_count?: number", source)
        self.assertIn("trade_log_archive_last_vacuumed?: boolean", source)
        self.assertIn("shadow_snapshot_block_reason?: string", source)
        self.assertIn("trade_log_archive_status?: string", source)
        self.assertIn("trade_log_archive_active_db_allocated_bytes?: number", source)
        self.assertIn("storage_trading_db_allocated_bytes?: number", source)
        self.assertIn("db_recovery_candidate_mode?: string", source)
        self.assertIn("post_promotion_promoted_at?: number", source)
        self.assertIn("post_promotion_baseline_at?: number", source)
        self.assertIn("post_promotion_boundary_action?: string", source)
        self.assertIn("post_promotion_boundary_source?: string", source)
        self.assertIn("post_promotion_boundary_reason?: string", source)
        self.assertIn("post_promotion_timing_skips?: number", source)
        self.assertIn("post_promotion_liquidity_skips?: number", source)
        self.assertIn("post_promotion_uncopyable_skip_rate?: number", source)
        self.assertIn("post_promotion_resolved_copied_count?: number", source)
        self.assertIn("post_promotion_resolved_copied_total_pnl_usd?: number", source)
        self.assertIn("post_promotion_evidence_ready?: boolean", source)
        self.assertIn("post_promotion_evidence_note?: string", source)
        self.assertIn("trust_tier?: string", source)
        self.assertIn("trust_size_multiplier?: number", source)
        self.assertIn("trust_note?: string", source)
        self.assertIn("export interface ConfigRow", source)
        self.assertIn("export interface ConfigSnapshot", source)
        self.assertIn("token_id?: string", source)
        self.assertIn("export interface ManualTradeResponse", source)
        self.assertIn("export interface DangerActionResponse", source)
        self.assertIn("export interface ModelTrainingRun", source)
        self.assertIn("export interface PerformancePosition", source)
        self.assertIn("export interface PerformanceSnapshot", source)
        self.assertIn("training_runs?: ModelTrainingRun[]", source)
        self.assertIn("stale_count?: number", source)
        self.assertIn("tracked_count?: number", source)
        self.assertIn("dropped_count?: number", source)
        self.assertIn("reactivated_count?: number", source)
        self.assertIn("promoted_count?: number", source)
        self.assertIn("export type RestartShadowWalletMode = 'keep_active' | 'keep_all' | 'clear_all'", source)
        self.assertIn("requestManualTradeCashOut", source)
        self.assertIn("action: 'cash_out'", source)
        self.assertIn("setLiveTradingEnabled", source)
        self.assertIn("requestTradeLogArchive", source)
        self.assertIn("requestShadowRestart", source)
        self.assertIn("requestRecoverDb", source)
        self.assertIn("requestDropWallet", source)
        self.assertIn("requestReactivateWallet", source)
        self.assertIn("fetchPerformanceSnapshot", source)
        self.assertIn("'/api/performance'", source)
        self.assertIn("'/api/wallets/drop'", source)
        self.assertIn("'/api/wallets/reactivate'", source)

    def test_mock_dashboard_defaults_dev_to_local_template_mode(self) -> None:
        source = MOCK_PATH.read_text(encoding="utf-8")
        self.assertIn("export const dashboardDataMode", source)
        self.assertIn("rawMode === 'api' ? 'api' : import.meta.env.DEV ? 'mock' : 'api'", source)
        self.assertIn("{id: 'tracker', label: '[1] TRACKER'}", source)
        self.assertIn("{id: 'signals', label: '[2] SIGNALS'}", source)
        self.assertIn("{id: 'perf', label: '[3] PERFORMANCE'}", source)
        self.assertIn("{id: 'models', label: '[4] MODEL'}", source)
        self.assertIn("{id: 'wallets', label: '[5] WALLETS'}", source)
        self.assertIn("{id: 'config', label: '[6] CONFIG'}", source)
        self.assertIn("const MOCK_EVENT_COUNT = 200", source)
        self.assertIn("Array.from({length: MOCK_EVENT_COUNT}", source)
        self.assertIn("trackerEvents: LiveEvent[]", source)
        self.assertIn("signalEvents: LiveEvent[]", source)
        self.assertIn("type: 'incoming'", source)
        self.assertIn("type: 'signal'", source)
        self.assertIn("trade_id: `trade-${1001 + index}`", source)
        self.assertIn("rows: editableConfigFields.map((field) => ({", source)
        self.assertIn("const extraManagedWallets = Array.from({length:", source)
        self.assertIn("const managedWalletRows = [...seedManagedWallets, ...extraManagedWallets]", source)
        self.assertIn("count: managedWalletRows.length", source)

    def test_config_fields_include_human_descriptions(self) -> None:
        source = CONFIG_FIELDS_PATH.read_text(encoding="utf-8")
        self.assertIn("export const configFieldDescriptions", source)
        self.assertIn("POLL_INTERVAL_SECONDS: 'How many seconds to wait before polling wallets and markets again.'", source)
        self.assertIn("MAX_MARKET_HORIZON: 'The longest time-to-resolution a market can have and still be eligible.'", source)
        self.assertIn("LOG_LEVEL: 'How verbose backend logging should be.'", source)
        self.assertIn("MAX_MARKET_EXPOSURE_FRACTION', label: 'Market Exposure Cap', kind: 'float', defaultValue: '0.20'", source)
        self.assertIn("MAX_TRADER_EXPOSURE_FRACTION', label: 'Trader Exposure Cap', kind: 'float', defaultValue: '0.30'", source)
        self.assertIn("MAX_TOTAL_OPEN_EXPOSURE_FRACTION', label: 'Open Exposure Cap', kind: 'float', defaultValue: '0.60'", source)
        self.assertIn("MAX_DAILY_LOSS_PCT', label: 'Daily Loss Drawdown', kind: 'float', defaultValue: '0.08'", source)

    def test_app_is_tabbed_dashboard_shell_with_api_hydration(self) -> None:
        source = APP_PATH.read_text(encoding="utf-8")
        self.assertIn("kelly-watcher", source)
        self.assertIn("Dashboard pages", source)
        self.assertIn("dashboardDataMode", source)
        self.assertIn("dashboardModel.pages.map", source)
        self.assertIn("topbar__nav", source)
        self.assertIn("page-canvas", source)
        self.assertIn("fetchBotState", source)
        self.assertIn("fetchConfigSnapshot", source)
        self.assertIn("fetchWalletSummary", source)
        self.assertIn("fetchTrackedWallets", source)
        self.assertIn("fetchDroppedWallets", source)
        self.assertIn("fetchPerformanceSnapshot", source)
        self.assertIn("BOT_STATE_POLL_INTERVAL_MS", source)
        self.assertIn("SNAPSHOT_POLL_INTERVAL_MS", source)
        self.assertIn("if (mode !== 'api')", source)
        self.assertIn("Promise.allSettled([", source)
        self.assertIn("useEventFeed", source)
        self.assertIn("const {events: pageEvents, loading: pageEventsLoading, error: pageEventsError} = useEventFeed(", source)
        self.assertIn("const mockPageEvents = useMemo(", source)
        self.assertIn("mockPageEvents", source)
        self.assertIn("event.type === 'incoming'", source)
        self.assertIn("event.type === 'signal'", source)
        self.assertIn("window.addEventListener('keydown', handleKeydown)", source)
        self.assertIn("target.tagName === 'INPUT'", source)
        self.assertIn("const pageIndex = Number.parseInt(event.key, 10)", source)
        self.assertIn("setActivePage(nextPage.id)", source)
        self.assertIn("<TrackerFeed", source)
        self.assertIn("events={trackerEvents}", source)
        self.assertIn("loading={pageEventsLoading}", source)
        self.assertIn("error={pageEventsError}", source)
        self.assertIn("bankrollUsd={botState.bankroll_usd}", source)
        self.assertIn("sourceLabel={mode === 'mock' ? 'MOCK FEED' : 'LIVE FEED'}", source)
        self.assertIn("<SignalsFeed", source)
        self.assertIn("events={signalEvents}", source)
        self.assertIn("{activePage === 'tracker' ? (", source)
        self.assertIn("{activePage === 'signals' ? (", source)
        self.assertIn("{activePage === 'perf' ? (", source)
        self.assertIn("{activePage === 'models' ? (", source)
        self.assertIn("{activePage === 'wallets' ? (", source)
        self.assertIn("{activePage === 'config' ? (", source)
        self.assertIn("<PerformancePage", source)
        self.assertIn("mode={mode}", source)
        self.assertIn("resolveConfidenceCutoff(configSnapshot)", source)
        self.assertIn("confidenceCutoff={confidenceCutoff}", source)
        self.assertIn("performanceResource={performanceResource}", source)
        self.assertIn("<ModelPage", source)
        self.assertIn("<WalletsPage", source)
        self.assertIn("<ConfigPage", source)
        self.assertIn("modelFallbackReason={botState.model_fallback_reason}", source)
        self.assertIn("shadowSnapshotBlockReason={botState.shadow_snapshot_block_reason}", source)
        self.assertIn("walletSummaryResource={mode === 'mock' ? readyResource(walletSummary || {ok: true}) : walletSummaryResource}", source)
        self.assertIn("trackedWalletsResource={mode === 'mock' ? readyResource(trackedWallets || {ok: true, wallets: []}) : trackedWalletsResource}", source)
        self.assertIn("droppedWalletsResource={mode === 'mock' ? readyResource(droppedWallets || {ok: true, wallets: []}) : droppedWalletsResource}", source)
        self.assertIn("managedWallets={managedWalletsForConfig}", source)
        self.assertIn("onBotStateChange={(nextState) => setBotStateResource(readyResource(nextState))}", source)
        self.assertNotIn("One backend, two frontends", source)
        self.assertNotIn("Recovery, integrity, and storage truth", source)
        self.assertNotIn("Restart Shadow", source)
        self.assertNotIn("Config Repair", source)
        self.assertNotIn("fetchManagedWallets", source)
        self.assertNotIn("fetchDiscoveryCandidates", source)
        self.assertNotIn("performanceSnapshot={performanceSnapshot}", source)
        self.assertNotIn("managedWallets={managedWallets}", source)
        self.assertNotIn("discoveryCandidates={discoveryCandidates}", source)
        self.assertNotIn("onManagedWalletsChange={setManagedWallets}", source)

    def test_dashboard_pages_module_implements_remaining_tabs(self) -> None:
        source = PAGES_PATH.read_text(encoding="utf-8")
        self.assertIn("useResizableColumns", source)
        self.assertIn("fitColumnsToViewport", source)
        self.assertIn("export function PerformancePage", source)
        self.assertIn("export function ModelPage", source)
        self.assertIn("export function WalletsPage", source)
        self.assertIn("export function ConfigPage", source)
        self.assertIn("saveConfigValue", source)
        self.assertIn("clearConfigValue", source)
        self.assertIn("CONFIG EDITOR", source)
        self.assertIn("config-editor__input", source)
        self.assertIn("config-editor__viewport", source)
        self.assertIn("DANGER ZONE", source)
        self.assertIn("RESET ALL TO DEFAULTS", source)
        self.assertIn("LIVE TRADING", source)
        self.assertIn("ARCHIVE TRADE LOG", source)
        self.assertIn("RESTART SHADOW", source)
        self.assertIn("RECOVER DB", source)
        self.assertIn("RESTART_SHADOW_OPTIONS", source)
        self.assertIn("resolveRecoveryCandidateMode", source)
        self.assertIn("setLiveTradingEnabled", source)
        self.assertIn("requestTradeLogArchive", source)
        self.assertIn("requestShadowRestart", source)
        self.assertIn("requestRecoverDb", source)
        self.assertIn("danger-zone__action", source)
        self.assertIn("danger-zone__select", source)
        self.assertIn("validateConfigDraftValue", source)
        self.assertIn("CONFIG_CHOICE_OPTIONS", source)
        self.assertIn("CONFIG_DURATION_OPTIONS", source)
        self.assertIn("configDiscreteOptions", source)
        self.assertIn("useConfigDiscreteDropdown", source)
        self.assertIn("title=\"PERFORMANCE\"", source)
        self.assertIn("title=\"MODEL\"", source)
        self.assertIn("title=\"WALLETS\"", source)
        self.assertIn("title=\"CONFIG\"", source)
        self.assertIn("className={joinClasses('wallet-page'", source)
        self.assertIn("title=\"BALANCE\"", source)
        self.assertIn("title=\"TRACKER STATS\"", source)
        self.assertIn("title=\"CURRENT POSITIONS\"", source)
        self.assertIn("title=\"PAST POSITIONS\"", source)
        self.assertIn("requestManualTradeCashOut", source)
        self.assertIn("marketId: event.market_id", source)
        self.assertIn("tokenId: String(event.token_id || '')", source)
        self.assertIn("potentialProfitForPosition", source)
        self.assertIn("label: 'PROFIT'", source)
        self.assertIn("label: 'EXIT NOW'", source)
        self.assertIn("dashboard-table__cell--compact dashboard-table__cell--flush", source)
        self.assertIn("formatMoney(row.pnl)", source)
        self.assertIn("performance-exit-button", source)
        self.assertIn("confidenceCutoff?: number", source)
        self.assertIn("cutoffRatioGradient(row.confidence, props.confidenceCutoff)", source)
        self.assertIn("moneyMetricColor(", source)
        self.assertIn("returnMetricColor(", source)
        self.assertIn("centeredRatioGradient(", source)
        self.assertIn("PERFORMANCE_STAT_TOOLTIPS", source)
        self.assertIn("MODEL_LABEL_TOOLTIPS", source)
        self.assertIn("configFieldDescriptions", source)
        self.assertIn("title={row.tooltip || row.label}", source)
        self.assertIn("performanceStatTooltip('START BALANCE')", source)
        self.assertIn("modelLabelTooltip('SCORED TRADES')", source)
        self.assertIn("description:", source)
        self.assertIn("configFieldDescriptions[field.key]", source)
        self.assertIn("title={row.description || row.label}", source)
        self.assertIn('<div className=\"config-editor__submeta\">{row.description}</div>', source)
        self.assertIn("BalanceChart", source)
        self.assertIn("balance-chart__scrub", source)
        self.assertIn("balance-chart__viewport", source)
        self.assertIn("formatMoney(selectedPoint.balance)", source)
        self.assertIn("at ${scrubTimeText} on ${scrubDayText}", source)
        self.assertIn("viewport.scrollLeft = viewport.scrollWidth", source)
        self.assertIn("const centerY = height / 2", source)
        self.assertNotIn("balance-chart__marker", source)
        self.assertIn("metric-grid", source)
        self.assertIn("title=\"RUNTIME\"", source)
        self.assertIn("title=\"QUALITY\"", source)
        self.assertIn("title=\"DECISIONS\"", source)
        self.assertIn("title=\"SHADOW GATE\"", source)
        self.assertIn("title=\"LATEST TRAINING\"", source)
        self.assertIn("title=\"TRAINING RUNS\"", source)
        self.assertIn("trainingRunRows", source)
        self.assertIn('tableId="model-training-runs"', source)
        self.assertIn("label: 'LOG LOSS'", source)
        self.assertIn("label: 'BRIER'", source)
        self.assertIn("label: 'DEPLOYED'", source)
        self.assertIn("latestTrainingRows", source)
        self.assertIn("CompactFieldList", source)
        self.assertIn('className="model-page"', source)
        self.assertIn("model-columns", source)
        self.assertIn("model-column", source)
        self.assertIn('className="dashboard-panel--model"', source)
        self.assertEqual(source.count('className="dashboard-column model-column"'), 5)
        self.assertIn('className="dashboard-column model-column model-column--span-2"', source)
        self.assertIn("START BALANCE", source)
        self.assertIn("const exposureRatio = currentBalance > 0 ? currentExposure / currentBalance : null", source)
        self.assertIn("const maxDrawdownRatio = useMemo(() => {", source)
        self.assertIn("label: 'MAX DRAWDOWN'", source)
        self.assertIn("const trackerStatsLeftRows = [", source)
        self.assertIn("const trackerStatsRightRows = [", source)
        self.assertIn('className="metric-grid__column"', source)
        self.assertIn("CURRENT BALANCE", source)
        self.assertIn("NET P&L", source)
        self.assertIn("REALIZED P&L", source)
        self.assertIn("AVAILABLE CASH", source)
        self.assertNotIn("label: 'OPEN POSITIONS'", source)
        self.assertIn("NEXT BLOCKER", source)
        self.assertIn("BEST WALLETS", source)
        self.assertIn("WORST WALLETS", source)
        self.assertIn("TRACKED WALLETS", source)
        self.assertIn("DROPPED WALLETS", source)
        self.assertIn("walletPnl", source)
        self.assertIn("walletCopyWinRate", source)
        self.assertIn("walletSkipRate", source)
        self.assertIn("walletStatusReason", source)
        self.assertIn("walletActionMessage", source)
        self.assertIn("requestDropWallet", source)
        self.assertIn("requestReactivateWallet", source)
        self.assertIn("mode: 'mock' | 'api'", source)
        self.assertIn("walletSummaryResource: LoadableResource<WalletSummaryResponse>", source)
        self.assertIn("trackedWalletsResource: LoadableResource<WalletRowsResponse>", source)
        self.assertIn("droppedWalletsResource: LoadableResource<WalletRowsResponse>", source)
        self.assertIn("onMockManagedWalletsChange?:", source)
        self.assertIn("COPY WR", source)
        self.assertIn("SKIP %", source)
        self.assertIn("LAST UPDATE", source)
        self.assertIn("label: 'USERNAME'", source)
        self.assertIn("color: () => resolveToneColor('negative')", source)
        self.assertIn("walletTone(row) === feedTheme.red ? feedTheme.red : undefined", source)
        self.assertIn("label: 'DROP'", source)
        self.assertIn("label: 'REACTIVATE'", source)
        self.assertIn("wallet-action-button", source)
        self.assertNotIn("{label: 'TRADE DB'", source)
        self.assertNotIn("{label: 'ARCHIVE DB'", source)
        self.assertNotIn("{label: 'SAVE DIR'", source)
        self.assertNotIn("{label: 'LOG DIR'", source)
        self.assertNotIn("{label: 'ACTIVE ROWS'", source)
        self.assertNotIn("{label: 'ARCHIVED'", source)
        self.assertIn("WATCHED WALLETS", source)
        self.assertIn("config-side-column", source)
        self.assertIn("config-editor__toggle-group", source)
        self.assertIn("config-editor__toggle--active", source)
        self.assertIn("config-editor__select", source)
        self.assertNotIn('title="MANAGED REGISTRY"', source)
        self.assertNotIn('title="DISCOVERY CANDIDATES"', source)
        self.assertIn('tableId="performance-current-positions"', source)
        self.assertIn('tableId="performance-past-positions"', source)
        self.assertIn('tableId="wallets-best"', source)
        self.assertIn('tableId="wallets-worst"', source)
        self.assertIn('tableId="wallets-tracked"', source)
        self.assertIn('tableId="wallets-dropped"', source)
        self.assertIn('tableId="config-watched-wallets"', source)
        self.assertIn("data-resizable-table-id={tableId}", source)
        self.assertIn("resize-head__handle", source)
        self.assertNotIn("title=\"MODEL OVERVIEW\"", source)

    def test_config_fields_include_full_editable_catalog(self) -> None:
        source = CONFIG_FIELDS_PATH.read_text(encoding="utf-8")
        self.assertIn("export const editableConfigFields", source)
        self.assertIn("POLL_INTERVAL_SECONDS", source)
        self.assertIn("HOT_WALLET_COUNT", source)
        self.assertIn("MIN_CONFIDENCE", source)
        self.assertIn("ALLOW_HEURISTIC", source)
        self.assertIn("ALLOW_XGBOOST", source)
        self.assertIn("MAX_BET_FRACTION", source)
        self.assertIn("SHADOW_BANKROLL_USD", source)
        self.assertIn("LIVE_REQUIRE_SHADOW_HISTORY", source)
        self.assertIn("RETRAIN_BASE_CADENCE", source)
        self.assertIn("MODEL_PATH", source)

    def test_feed_utils_own_shared_event_polling(self) -> None:
        source = FEED_UTILS_PATH.read_text(encoding="utf-8")
        self.assertIn("fetchApiJson<EventsResponse>", source)
        self.assertIn("'/api/events?max=250'", source)
        self.assertIn("export function useEventFeed", source)
        self.assertIn("if (mode !== 'mock')", source)
        self.assertIn("if (mode !== 'api')", source)
        self.assertIn("}, [mockEvents, mode])", source)
        self.assertIn("}, [mode])", source)
        self.assertIn("export function normalizeReasonText", source)
        self.assertIn("export function resolveActionText", source)
        self.assertIn("export function buildTradeIdLookup", source)

    def test_tracker_feed_ports_cli_columns_using_semantic_table_layout(self) -> None:
        source = TRACKER_PATH.read_text(encoding="utf-8")
        self.assertIn("moneyMetricColor", source)
        self.assertIn("bankrollUsd?: number", source)
        self.assertIn("loading: FeedEventsState['loading']", source)
        self.assertIn("error: FeedEventsState['error']", source)
        self.assertIn("sourceLabel = 'LIVE FEED'", source)
        self.assertIn("useResizableColumns('tracker-feed', TRACKER_COLUMNS)", source)
        self.assertIn("const TRACKER_COLUMNS: TrackerColumn[] = [", source)
        self.assertIn("events.filter((event) => event.type === 'incoming').reverse()", source)
        self.assertIn('className="tracker-table"', source)
        self.assertIn('data-resizable-table-id="tracker-feed"', source)
        self.assertIn("<colgroup>", source)
        self.assertIn("TRACKER_COLUMNS.map((column) => (", source)
        self.assertIn("tracker-cell__content", source)
        self.assertIn('data-column-key={column.key}', source)
        self.assertIn("resize-head__handle", source)
        self.assertIn("onPointerDown={(event) => startResize(column, event)}", source)
        self.assertIn("label: 'ID'", source)
        self.assertIn("label: 'TIME'", source)
        self.assertIn("label: 'USERNAME'", source)
        self.assertIn("label: 'MARKET'", source)
        self.assertIn("label: 'ACTN'", source)
        self.assertIn("label: 'SIDE'", source)
        self.assertIn("label: 'PRICE'", source)
        self.assertIn("label: 'SHARES'", source)
        self.assertIn("label: 'PAID'", source)
        self.assertIn("label: 'TO WIN'", source)
        self.assertIn("label: 'PROFIT'", source)
        self.assertIn("probabilityColor(event.price)", source)
        self.assertIn("outcomeColor", source)
        self.assertNotIn("useEventFeed(", source)
        self.assertNotIn("TRACKER_TABLE_WIDTH", source)
        self.assertNotIn("gridTemplateColumns", source)

    def test_signals_feed_ports_cli_columns_using_semantic_table_layout(self) -> None:
        source = SIGNALS_PATH.read_text(encoding="utf-8")
        self.assertIn("loading: FeedEventsState['loading']", source)
        self.assertIn("error: FeedEventsState['error']", source)
        self.assertIn("sourceLabel = 'LIVE FEED'", source)
        self.assertIn("useResizableColumns('signals-feed', SIGNALS_COLUMNS)", source)
        self.assertIn("const SIGNALS_COLUMNS: SignalsColumn[] = [", source)
        self.assertIn("events.filter((event) => event.type === 'signal').reverse()", source)
        self.assertIn("event.type === 'incoming' && event.action?.trim()", source)
        self.assertIn('className="signals-table"', source)
        self.assertIn('data-resizable-table-id="signals-feed"', source)
        self.assertIn("<colgroup>", source)
        self.assertIn("SIGNALS_COLUMNS.map((column) => (", source)
        self.assertIn("signals-cell__content", source)
        self.assertIn('data-column-key={column.key}', source)
        self.assertIn("resize-head__handle", source)
        self.assertIn("onPointerDown={(event) => startResize(column, event)}", source)
        self.assertIn("label: 'ID'", source)
        self.assertIn("label: 'TIME'", source)
        self.assertIn("label: 'USERNAME'", source)
        self.assertIn("label: 'MARKET'", source)
        self.assertIn("label: 'ACTN'", source)
        self.assertIn("label: 'SIDE'", source)
        self.assertIn("label: 'PRICE'", source)
        self.assertIn("label: 'SHARES'", source)
        self.assertIn("label: 'TOTAL'", source)
        self.assertIn("label: 'CONF'", source)
        self.assertLess(source.index("label: 'CONF'"), source.index("label: 'DEC'"))
        self.assertIn("label: 'DEC'", source)
        self.assertIn("label: 'REASON'", source)
        self.assertIn("decisionColor", source)
        self.assertIn("normalizeReasonText", source)
        self.assertIn("probabilityColor", source)
        self.assertIn("outcomeColor", source)
        self.assertNotIn("useEventFeed(", source)

    def test_styles_are_now_a_solid_background_with_simple_topbar(self) -> None:
        source = STYLES_PATH.read_text(encoding="utf-8")
        self.assertIn("--bg: #0f0f0f;", source)
        self.assertIn("background: var(--bg);", source)
        self.assertIn("text-transform: uppercase;", source)
        self.assertIn("overflow: hidden;", source)
        self.assertIn(".topbar {", source)
        self.assertIn(".topbar__link--active {", source)
        self.assertIn("border-right: 1px solid var(--border);", source)
        self.assertIn(".tracker-table,", source)
        self.assertIn("table-layout: fixed;", source)
        self.assertIn(".dashboard-table__content {", source)
        self.assertIn(".signals-table,", source)
        self.assertNotIn("width: max-content;", source)
        self.assertIn(".dashboard-stats,", source)
        self.assertIn(".dashboard-panel__body {", source)
        self.assertIn(".dashboard-panels--two {", source)
        self.assertIn(".dashboard-panels--config {", source)
        self.assertIn(".config-page {", source)
        self.assertIn(".config-panels-main {", source)
        self.assertIn(".dashboard-panel--config-watched .dashboard-table__viewport {", source)
        self.assertIn(".dashboard-panel--danger-zone {", source)
        self.assertIn(".danger-zone__button {", source)
        self.assertIn("align-items: start;", source)
        self.assertIn("scrollbar-width: none;", source)
        self.assertIn(".tracker-head::-webkit-scrollbar,", source)
        self.assertIn(".resize-head {", source)
        self.assertIn(".resize-head__handle {", source)
        self.assertIn(".resize-head__handle::before {", source)
        self.assertIn("top: 0.28rem;", source)
        self.assertIn("bottom: 0.28rem;", source)
        self.assertIn("cursor: col-resize;", source)
        self.assertIn(".dashboard-table__cell--flush {", source)
        self.assertIn("padding: 0;", source)
        self.assertIn("margin: 0;", source)
        self.assertIn("height: 100%;", source)
        self.assertIn(".metric-grid {", source)
        self.assertIn(".metric-grid__row {", source)
        self.assertIn(".dashboard-panel--performance-stats .metric-grid {", source)
        self.assertIn("gap: 0.18rem 1rem;", source)
        self.assertIn(".compact-field-list {", source)
        self.assertIn(".compact-field-list__pair {", source)
        self.assertIn(".model-columns {", source)
        self.assertIn("grid-template-columns: repeat(5, minmax(0, 1fr));", source)
        self.assertIn(".dashboard-panel--model .compact-field-list__label {", source)
        self.assertIn("text-overflow: ellipsis;", source)
        self.assertIn(".dashboard-panel--model-runs .dashboard-table__viewport {", source)

    def test_column_resize_hook_persists_schema_safe_drag_widths_with_no_double_click(self) -> None:
        source = COLUMN_RESIZE_PATH.read_text(encoding="utf-8")
        self.assertIn("export interface ResizableColumnSpec", source)
        self.assertIn("interface PersistedColumnWidths", source)
        self.assertIn("const COLUMN_WIDTHS_STORAGE_VERSION = 2", source)
        self.assertIn("function storageKeyForTable", source)
        self.assertIn("kelly-watcher:column-widths:v${COLUMN_WIDTHS_STORAGE_VERSION}:${tableId}", source)
        self.assertIn("function readPersistedWidths", source)
        self.assertIn("window.localStorage.getItem", source)
        self.assertIn("window.localStorage.setItem", source)
        self.assertIn("window.localStorage.removeItem", source)
        self.assertIn("parsed.columnKeys.join('|') !== columns.map((column) => column.key).join('|')", source)
        self.assertIn("const [widths, setWidths] = useState<ColumnWidths | null>(() => readPersistedWidths(tableId, columns))", source)
        self.assertIn("useEffect(() => {", source)
        self.assertIn("function measureTableWidths", source)
        self.assertIn("horizontalPadding", source)
        self.assertIn("function contentWidth", source)
        self.assertIn("contentWidth(headerLabel)", source)
        self.assertIn("table.querySelectorAll<HTMLTableCellElement>(`tbody tr td:nth-child(${index + 1})`)", source)
        self.assertIn("setWidths(measuredWidths)", source)
        self.assertIn("[data-resizable-table-id", source)
        self.assertIn("data-column-key", source)
        self.assertIn("const tableWidth = useMemo(() => {", source)
        self.assertIn("Math.max(0, Math.round(startWidth + (moveEvent.clientX - startX)))", source)
        self.assertIn("window.addEventListener('pointermove', handlePointerMove)", source)
        self.assertIn("window.addEventListener('pointerup', handlePointerUp)", source)
        self.assertNotIn("onHeaderDoubleClick", source)
        self.assertNotIn("viewport.clientWidth", source)

    def test_browser_tab_title_stays_lowercase(self) -> None:
        source = INDEX_PATH.read_text(encoding="utf-8")
        self.assertIn("<title>kelly-watcher</title>", source)
        self.assertNotIn("<title>Kelly Watcher Web Dashboard</title>", source)


if __name__ == "__main__":
    unittest.main()
